spring:
  autoconfigure:
    exclude:
    - org.springframework.boot.actuate.autoconfigure.metrics.export.stackdriver.StackdriverMetricsExportAutoConfiguration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/devdb?currentSchema=public
    username: user1
    password: pw123456
  jpa:
    show-sql: true
  main:
    banner-mode: console
  cloud:
    gcp:
      core:
        enabled: false
      sql:
        enabled: false
      metrics:
        enabled: false
      trace:
        enabled: false
      logging:
        enabled: false
  redis:
    host: 127.0.0.1
    port: 6378
    password: pw123456
  cache:
    redis:
      time-to-live: 600000 # Configure default TTL, e.g., 10 minutes

logging:
  level:
    root: info
    com.example.demo: debug
    com.zaxxer.hikari.pool.HikariPool: debug

management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    git:
      mode: full
  
